-- Autogenerated by migration tool on 2022-05-23 11:10:18
-- CHANGEME: Verify or edit this file before proceeding

-- Resource: container.clusters
DROP TABLE IF EXISTS gcp_container_cluster_autoscaling_resource_limits;
DROP TABLE IF EXISTS gcp_container_cluster_conditions;
DROP TABLE IF EXISTS gcp_container_cluster_master_authorized_networks_cidr_blocks;
DROP TABLE IF EXISTS gcp_container_cluster_node_pool_conditions;
DROP TABLE IF EXISTS gcp_container_cluster_node_pool_config_taints;
DROP TABLE IF EXISTS gcp_container_cluster_node_pools;
DROP TABLE IF EXISTS gcp_container_clusters;
