-- Autogenerated by migration tool on 2022-04-11 17:51:46
-- CHANGEME: Verify or edit this file before proceeding

-- Resource: compute.instance_groups
DROP TABLE IF EXISTS gcp_compute_instance_group_instances;
DROP TABLE IF EXISTS gcp_compute_instance_groups;
