-- Autogenerated by migration tool on 2022-04-04 11:17:00
-- CHANGEME: Verify or edit this file before proceeding

-- Resource: storage.buckets
ALTER TABLE IF EXISTS "gcp_storage_buckets"
    ADD COLUMN IF NOT EXISTS "encryption_type" text;

-- Resource: compute.instance_groups
CREATE TABLE IF NOT EXISTS "gcp_compute_instance_groups"
(
    "cq_id"              uuid NOT NULL,
    "cq_meta"            jsonb,
    "project_id"         text,
    "creation_timestamp" text,
    "description"        text,
    "fingerprint"        text,
    "id"                 bigint,
    "kind"               text,
    "name"               text,
    "named_ports"        jsonb,
    "network"            text,
    "region"             text,
    "self_link"          text,
    "size"               bigint,
    "subnetwork"         text,
    "zone"               text,
    CONSTRAINT gcp_compute_instance_groups_pk PRIMARY KEY (cq_id),
    UNIQUE (cq_id)
);
CREATE TABLE IF NOT EXISTS "gcp_compute_instance_group_instances"
(
    "cq_id"                uuid NOT NULL,
    "cq_meta"              jsonb,
    "instance_group_cq_id" uuid,
    "instance"             text,
    "named_ports"          jsonb,
    "status"               text,
    CONSTRAINT gcp_compute_instance_group_instances_pk PRIMARY KEY (cq_id),
    UNIQUE (cq_id),
    FOREIGN KEY (instance_group_cq_id) REFERENCES gcp_compute_instance_groups (cq_id) ON DELETE CASCADE
);
