-- Autogenerated by migration tool on 2022-05-08 09:18:39
-- CHANGEME: Verify or edit this file before proceeding

-- Resource: cloudbilling.accounts
DROP TABLE IF EXISTS gcp_billing_accounts;

-- Resource: cloudbilling.services
DROP TABLE IF EXISTS gcp_cloudbilling_service_sku_pricing_info_tiered_rates;
DROP TABLE IF EXISTS gcp_cloudbilling_service_sku_pricing_info;
DROP TABLE IF EXISTS gcp_cloudbilling_service_skus;
DROP TABLE IF EXISTS gcp_cloudbilling_services;
