-- Autogenerated by migration tool on 2022-05-08 09:18:39
-- CHANGEME: Verify or edit this file before proceeding

-- Resource: cloudbilling.accounts
CREATE TABLE IF NOT EXISTS "gcp_billing_accounts" (
	"cq_id" uuid NOT NULL,
	"cq_meta" jsonb,
	"display_name" text,
	"master_billing_account" text,
	"name" text,
	"open" boolean,
	"project_billing_enabled" boolean,
	"project_name" text,
	"project_id" text,
	CONSTRAINT gcp_billing_accounts_pk PRIMARY KEY(cq_id),
	UNIQUE(cq_id)
);
