on:
  push:
    branches:
      - main
      - chore/release_pr

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: go
          package-name: cq-provider-gcp
          token: ${{ secrets.GH_CQ_BOT }}
          pull-request-title-pattern: "chore${scope}: Release${component} ${version}"
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
