# DONT EDIT. This file is synced from https://github.com/cloudquery/.github/.github
name: terraform_apply
on:
  push:
    branches:
      - main

jobs:
  terrafrom_apply:
    permissions:
        id-token: write
        contents: read    # This is required for actions/checkout@v2
    name: Terrafrom Apply
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'id_token'
          workload_identity_provider: 'projects/163549298763/locations/global/workloadIdentityPools/cq-provider-gcp-github-action/providers/github-action-provider'
          service_account: 'cq-provider-gcp-github@cq-provider-gcp.iam.gserviceaccount.com'

      # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@master'
        export_default_credentials: true
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        id: plan
        run: terraform apply -no-color

